"""Reports page: Excel + PDF generation with download buttons."""
from __future__ import annotations

import streamlit as st

from config.settings import settings
from reporting import metrics
from reporting.narrative import build_narrative
from ui.common import empty_state, needs_data


def render(conn):
    st.title("📄 Client Reports")
    if needs_data(conn):
        empty_state("No campaign data to report on yet.")
        return

    camp = conn.execute("SELECT * FROM campaigns LIMIT 1").fetchone()
    tag = f"{camp['client_name'].replace(' ', '_')}_{camp['campaign_name'].replace(' ', '_')}"

    st.markdown("""
**Every figure in these reports is recomputed from the reconciled database.**
Narrative text may be AI-assisted when Groq/Gemini/Qwen is configured, but numbers are
never generated by a language model.""")

    st.divider()
    c1, c2 = st.columns(2)

    with c1:
        st.subheader("Excel reconciliation workbook")
        st.caption("Sheets: Campaign Summary · Creators · Deliverables · Analytics · "
                   "Financial Reconciliation · Exceptions")
        if st.button("📗 Generate Excel Report", type="primary"):
            from reporting.excel import export_excel
            try:
                out = settings.outputs_dir / f"starfish_reconciliation_{tag}.xlsx"
                export_excel(conn, out)
                st.session_state["excel_blob"] = out.read_bytes()
                st.session_state["excel_name"] = out.name
                st.success(f"Workbook written to {out}")
            except Exception as exc:
                st.error(f"Excel generation failed: {exc}")
        if st.session_state.get("excel_blob"):
            st.download_button("⬇️ Download Excel (.xlsx)",
                               st.session_state["excel_blob"],
                               file_name=st.session_state["excel_name"],
                               mime="application/vnd.openxmlformats-officedocument."
                                    "spreadsheetml.sheet")

    with c2:
        st.subheader("PDF client report")
        st.caption("Cover · Campaign Overview · Performance · Creator & Content "
                   "Performance · Deliverables · Financials · Exceptions · "
                   "Key Findings · Recommendations")
        if st.button("📕 Generate PDF Report", type="primary"):
            from reporting.pdf import generate_pdf
            try:
                out = settings.outputs_dir / f"starfish_campaign_report_{tag}.pdf"
                generate_pdf(conn, out)
                st.session_state["pdf_blob"] = out.read_bytes()
                st.session_state["pdf_name"] = out.name
                st.success(f"Report written to {out}")
            except Exception as exc:
                st.error(f"PDF generation failed: {exc}")
        if st.session_state.get("pdf_blob"):
            st.download_button("⬇️ Download PDF (.pdf)", st.session_state["pdf_blob"],
                               file_name=st.session_state["pdf_name"], mime="application/pdf")

    st.divider()
    st.subheader("Executive summary preview")
    nar = build_narrative(conn)
    st.markdown(f"*Narrative source: **{nar.get('source', 'deterministic template')}***")
    st.markdown(nar["executive_summary"])
    with st.expander("Key observations & recommendations"):
        for o in nar["key_observations"]:
            st.markdown(f"- 🔍 {o}")
        for o in nar["operational_observations"]:
            st.markdown(f"- ⚙️ {o}")
        st.markdown("**Recommendations**")
        for i, r in enumerate(nar["recommendations"], 1):
            st.markdown(f"{i}. {r}")

    t = metrics.campaign_totals(conn)
    st.caption(f"Report figures validated against live totals: {t['views']:,} views · "
               f"{t['engagements']:,} engagements · ${t['contracted_fees']:,.0f} contracted · "
               f"{t['open_exceptions']} open exceptions.")
